apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podlands
  namespace: flux-system
spec:
  git:
    checkout:
      ref: master
    commit:
      author:
        email: qoutland@gmail.com
        name: Qoutland
    push:
      branch: master
  update:
    path: ./clusters/prod/podlands
    strategy: Setters
