apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: podlands
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: podlands
  git:
    commit:
      author:
        email: qoutland@gmail.com
        name: Qoutland
    push:
      branch: master
  update:
    path: ./clusters/prod/podlands
    strategy: Setters
