apiVersion: v1
kind: Service
metadata:
  name: {{ include "podlands.name" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.backend.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{ .Values.backend.selector | toYaml | nindent 4 }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http