{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podlands.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "podlands.name" . }}
data:
{{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
