apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podlands.name" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.frontend.labels | toYaml | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  {{- if not .Values.frontend.deployment.autoscaling.enabled }}
  replicas: {{ .Values.frontend.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ .Values.frontend.labels | toYaml | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ .Values.frontend.labels | toYaml | nindent 8 }}
    spec:
      {{- with .Values.frontend.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.frontend.name }}
          {{- with .Values.frontend.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "podlands.name" . }}-config
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          {{- with .Values.frontend.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}