apiVersion: v1
kind: Service
metadata:
  name: {{ include "podlands.name" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.frontend.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{ .Values.frontend.service.selector | toYaml | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http