apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.serviceAccount.labels | toYaml }}
  annotations:
    {{ .Values.serviceAccount.annotations | toYaml }}
--- 
# Role for {{ .Values.serviceAccount.name }} to deploy to {{ .Values.namespace }} namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}-role
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.serviceAccount.labels | toYaml }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Role binding for backend to deploy to snake namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rb
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io