apiVersion: v1
kind: Namespace
metadata:
  name: arena
  labels:
    environment: production
    team: qoutland
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: arena
  name: chaos-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-binding
  namespace: arena
subjects:
  - kind: ServiceAccount
    name: chaos-api
    namespace: website
roleRef:
  kind: Role
  name: chaos-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: arena
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
