# Role for backend to deploy to snake namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: {{ .Values.snake_namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Role binding for backend to deploy to snake namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rb
  namespace: {{ .Values.snake_namespace }}
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
# Service account for backend to deploy to snake namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: {{ .Values.namespace }}
---
# Deployment for backend to deploy to snake namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podlands-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podlands-backend
  template:
    metadata:
      labels:
        app: podlands-backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: podlands-backend
          image: docker.io/qoutland/podlands-be:{{ .Values.tag }}
          imagePullPolicy: Never
---
# Podlands backend service
apiVersion: v1
kind: Service
metadata:
  name: podlands-backend
  namespace: {{ .Values.namespace }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
