apiVersion: apps/v1
kind: Deployment
metadata:
  name: podlands-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podlands-frontend
  template:
    metadata:
      labels:
        app: podlands-frontend
    spec:
      containers:
        - name: podlands-frontend
          image: docker.io/qoutland/podlands-fe:{{ .Values.tag }}
          imagePullPolicy: Never
---
# Podlands frontend service
apiVersion: v1
kind: Service
metadata:
  name: podlands-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: podlands-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
