apiVersion: v1
kind: Namespace
metadata:
  name: website 
  labels:
    environment: development
    team: qoutland
---
apiVersion: v1
kind: Namespace
metadata:
  name: snake
  labels:
    environment: development
    team: qoutland