apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    environment: development
    team: qoutland
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.snake_namespace }}
  labels:
    environment: development
    team: qoutland