name: Build Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      run: docker build backend/ --file backend/Dockerfile --tag qoutland/podlands-be:$(date +%s)
    - name: Push the backend Docker image
      run: docker push qoutland/podlands-be:$(date +%s)

    - name: Build the frontend Docker image
      run: docker build frontend/ --file frontend/Dockerfile --tag qoutland/podlands-fe:$(date +%s)
    - name: Push the frontend Docker image
      run: docker push qoutland/podlands-fe:$(date +%s)

    - name: Build the snake Docker image
      run: docker build snake/ --file snake/Dockerfile --tag qoutland/podlands-snake:$(date +%s)
    - name: Push the snake Docker image
      run: docker push qoutland/podlands-snake:$(date +%s)