name: Build Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Login to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - uses: actions/checkout@v4

    - name: Set tag using date
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the backend Docker image
      run: docker build backend/ --file backend/Dockerfile --tag ghcr.io/qoutland/podlands/backend:$TAG
    - name: Push the backend Docker image
      run: docker push ghcr.io/qoutland/podlands/backend:$TAG

    - name: Build the frontend Docker image
      run: docker build frontend/ --file frontend/Dockerfile --tag ghcr.io/qoutland/podlands/frontend:$TAG
    - name: Push the frontend Docker image
      run: docker push ghcr.io/qoutland/podlands/frontend:$TAG

    - name: Build the snake Docker image
      run: docker build snake/ --file snake/Dockerfile --tag ghcr.io/qoutland/podlands/snake:$TAG
    - name: Push the snake Docker image
      run: docker push ghcr.io/qoutland/podlands/snake:$TAG